config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:destroy, :show, :edit, :update] do
    get 'withdrawal'
  end
  resources :categories do
    resources :topics do
      resources :posts, only: [:create, :destroy]
    end
  end
  get 'home/about' => 'home#about'
  root 'home#top'
  resources :politicians

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/constituency.rb
class Constituency < ApplicationRecord
    has_many :politicians
end

app/models/election_history.rb
class ElectionHistory < ApplicationRecord
    belongs_to :event
    belongs_to :party
    belongs_to :politician_classification
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :election_histories
end

app/models/party.rb
class Party < ApplicationRecord
    has_many :politicians
    has_many :election_histories

end

app/models/politician.rb
class Politician < ApplicationRecord
    belongs_to :constituency
    belongs_to :politician_classification
    belongs_to :party
end

app/models/politician_classification.rb
class PoliticianClassification < ApplicationRecord
    has_many :election_histories
    has_many :politicians
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts
    belongs_to :user
    belongs_to :category

    attachment :topic_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :topics
  has_many :user_events

  attachment :user_image
  
  enum gender: {man:0, woman:1, custom:2}

  REGISTRABLE_ATTRIBUTES = %i(
    last_name
    first_name
    email
    gender
    age
  )
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/models/watch.rb
class Watch < ApplicationRecord    belongs_to :event
    belongs_to :user
    belongs_to :politician
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
    end
    def create
        topic = Topic.find(params[:topic_id])
        post = current_user.posts.new(topic_post_params)
        post.topic_id = topic.id
        post.save
        redirect_to category_topic_path(topic.category_id, topic)
    end
    def edit
    end
    def update
    end
    def destroy
        post = Post.find(params[:id])
        if post.user_id == current_user.id
            post.destroy
            redirect_to category_topic_path(post.topic.category_id, post.topic_id)
        else
            redirect_to category_topic_path(post.topic.category_id, post.topic_id)
        end
    end

    private
    def topic_post_params
        params.require(:post).permit(:user_id, :topic_id, :content)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def show
        @category = Category.find(params[:category_id])
        @topic = Topic.find(params[:id])        
        @topic_post = Post.new
        end
    def new
    end
    def create
        category = Category.find(params[:category_id])
        topic = current_user.topics.new(category_topic_params)
        topic.category_id = category.id
        topic.save
        redirect_to category_topic_path(category,topic)
    end
    def edit
    end
    def update
    end
    def destory
    end

    private
    def category_topic_params
        params.require(:topic).permit(:user_id, :category_id, :topic, :explanation, :topic_image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "You cannot edit"
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
		@user_id = current_user.id
		if @user.update(user_params)
			flash[:notice] = "You have updated user successfully."
			redirect_to user_path(@user.id)
		else
			flash[:notice] = "error."
			render("users/edit")
		end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(User::REGISTRABLE_ATTRIBUTES)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/show.html.erb
<%= link_to "トピック一覧へ", category_path(@topic.category_id) %>
<br>
<%= attachment_image_tag @topic, :topic_image, fallback: "no_image.jpg", format:'jpeg', size: "120x120" %>
<h1><%= @topic.topic %></h1>
<%= @topic.explanation %>
<table class="table">
    <thead>
        <tr>
            <th>コメント</th>
        </tr>
    </thead>
    <tbody>
        <% @topic.posts.each do |post| %>
        <tr>
            <td>
                <%= attachment_image_tag post.user, :user_image, fallback: "no_image.jpg", format:'jpeg', size: "40x40", class: "icon" %>
                <%= post.user.first_name %>
                <%= post.content %>
            </td>
            <td>
                <% if post.user_id == current_user.id %>
                    <%= link_to "削除", category_topic_post_path(@topic.category_id, @topic, post),
method: :delete, "data-confirm" => "本当に削除しますか？" %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<% if user_signed_in? %>
    <%= form_for [@category, @topic, @topic_post] do |f| %>
        <div class="row">
            <div>
                <%= f.text_field :content, rows:'3', class: "form-control",placeholder: "コメント" %>
            </div>
        </div>
        <%= f.submit "コメントする", class: "btn btn-primary btn-base-1 mt-20 pull-right" %>
    <% end %>
<% end %>