config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:destroy, :show, :edit, :update] do
    get 'withdrawal'
  end
  resources :categories do
    resources :topics do
      resources :posts, only: [:create, :destroy]
    end
  end
  get 'home/about' => 'home#about'
  root 'home#top'
  resources :politicians

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :topics
  has_many :user_events

  attachment :user_image
  
  enum gender: {man:0, woman:1, custom:2}

  REGISTRABLE_ATTRIBUTES = %i(
    last_name
    first_name
    email
    gender
    age
  )
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "You cannot edit"
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
		@user_id = current_user.id
		if @user.update(user_params)
			flash[:notice] = "You have updated user successfully."
			redirect_to user_path(@user.id)
		else
			flash[:notice] = "error."
			render("users/edit")
		end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(User::REGISTRABLE_ATTRIBUTES)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>ユーザー情報編集</h2>
<%= form_for(@user) do |f| %>
    <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :user_image %>
    </div>
    <div class="field">
        <%= f.label "名前" %>
        <label>姓
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></label>名
        <label><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></label>
    </div>
    <div class="field">
        <%= f.label "カナ" %>
        <label>セイ
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %></label>
        <label>メイ
        <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %></label>
    </div>
    <div class="field">
        <%= f.label "メールアドレス" %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
    <div class="field">
        <%= f.label "性別" %><br />
        <label><%= f.radio_button :gender, :man %> 男 </label>
        <label><%= f.radio_button :gender, :woman %> 女</label>
        <label><%= f.radio_button :gender, :custom %> その他</label>
    </div>
    <div class="field">
        <%= f.label "年齢" %><br />
        <%= f.number_field :age, autofocus: true, autocomplete: "age" %>
    </div>
    <%= f.submit '更新' %>
<% end %>

app/views/users/show.html.erb
<div class="col-xs-10">
    <h1> マイページ</h1>
    <div class="col-xs-5 border" style="margin-right: 50px;">
        <h4> ユーザ情報</h4>
        <%= attachment_image_tag @user, :user_image, fallback: "no_image.jpg", format:'jpeg', size: "100x100" %>
        <div class="field">
            <label>
                名前 : <%= @user.last_name + @user.first_name %>
            </label>
            <br>
            <label>メールアドレス : <%= @user.email %></label>
            <br>
            <label>性別 : <%= @user.gender_i18n %></label>
            <br>
            <label>年齢 : <%= @user.age %></label>
        </div>
        <%= link_to "編集" , edit_user_path(@user) %>
    </div>
    <div class="col-xs-10">
        <%= link_to "退会する", user_withdrawal_path(@user) %>
    </div>
</div>

app/views/users/withdrawal.html.erb
<h1> 本当に退会しますか？</h1>
<p> 退会したアカウントではログインできません。</p>

<%= link_to "退会する", user_path(current_user), method: :delete, 
"data-confirm" => "本当に退会しますか？" %>