config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:destroy, :show, :edit, :update] do
    get 'withdrawal'
  end
  resources :categories do
    resources :topics do
      resources :posts, only: [:create, :destroy]
    end
  end
  get 'home/about' => 'home#about'
  root 'home#top'
  resources :politicians

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/constituency.rb
class Constituency < ApplicationRecord
    has_many :politicians
end

app/models/election_history.rb
class ElectionHistory < ApplicationRecord
    belongs_to :event
    belongs_to :party
    belongs_to :politician_classification
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :election_histories
end

app/models/party.rb
class Party < ApplicationRecord
    has_many :politicians
    has_many :election_histories

end

app/models/politician.rb
class Politician < ApplicationRecord
    belongs_to :constituency
    belongs_to :politician_classification
    belongs_to :party
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts
    belongs_to :user
    belongs_to :category

    attachment :topic_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :topics
  has_many :user_events

  attachment :user_image
  
  enum gender: {man:0, woman:1, custom:2}

  REGISTRABLE_ATTRIBUTES = %i(
    last_name
    first_name
    email
    gender
    age
  )
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
    belongs_to :event
    belongs_to :user
end

app/models/watch.rb
class Watch < ApplicationRecord    belongs_to :event
    belongs_to :user
    belongs_to :politician
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
    end
    def create
        topic = Topic.find(params[:topic_id])
        post = current_user.posts.new(topic_post_params)
        post.topic_id = topic.id
        post.save
        redirect_to category_topic_path(topic.category_id, topic)
    end
    def edit
    end
    def update
    end
    def destroy
        post = Post.find(params[:id])
        if post.user_id == current_user.id
            post.destroy
            redirect_to category_topic_path(post.topic.category_id, post.topic_id)
        else
            redirect_to category_topic_path(post.topic.category_id, post.topic_id)
        end
    end

    private
    def topic_post_params
        params.require(:post).permit(:user_id, :topic_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PJapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="header" class="">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <p class="navbar-brand">Electal</p>
          </div>
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to " Your Account", user_path(current_user.id), class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to " カテゴリー一覧", categories_path, class: "glyphicon glyphicon-th" %></li>
              <li><%= link_to " 政治家一覧", politicians_path, class: "glyphicon glyphicon-th" %></li>

            <% else %>
              <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home" %> </li>
              <li><%= link_to " About", home_about_path, class: "glyphicon glyphicon-link" %></li>
              <li><%= link_to " カテゴリー一覧", categories_path, class: "glyphicon glyphicon-th" %></li>
              <li><%= link_to " 政治家一覧", politicians_path, class: "glyphicon glyphicon-user" %></li>
              <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out itemsize" %></li>
            <% else %>
              <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div class="container body">
          <%= yield %>
    </div>
  </body>
</html>